name: GitHub packages workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  package:
    name: Create and push packages ⚙️
    runs-on: ubuntu-latest
    permissions:
      packages: write

    outputs:
      version: ${{ steps.version-generator.outputs.version }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Set Version Number
      id: version-generator
      run: echo "version=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT
  
    - name: Create artifacts folder
      run: |
        mkdir "$GITHUB_WORKSPACE/artifacts"
        mkdir "$GITHUB_WORKSPACE/artifacts/Octopub.Frontend"
        cp *.yml "$GITHUB_WORKSPACE/artifacts/Octopub.Frontend"

    - name: Package Octopub.Frontend 🐙
      uses: OctopusDeploy/create-nuget-package-action@v3
      with:
        package_id: "Octopub.Frontend"
        version: "${{ steps.version-generator.outputs.version }}"
        output_folder: "${{ github.workspace }}/artifacts"
        base_path: "${{ github.workspace }}/artifacts/Octopub.Frontend"
        files: |
          **/*.*
        nuspec_description: Octopub Frontend
        nuspec_authors: |
          Ryan Rousseau

    - name: Publish Artifacts to Development
      run: |
        dotnet nuget push "$GITHUB_WORKSPACE/artifacts/Octopub.Frontend.${{ steps.version-generator.outputs.version }}.nupkg" --source "https://nuget.pkg.github.com/ryanrousseau/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}

  push-build-information:
    name: Push Build Information to Octopus 🐙
    needs: package 
    runs-on: ubuntu-latest
      
    env:
      OCTOPUS_URL: ${{ vars.OCTOPUS_SERVER_URL }}
      OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
      OCTOPUS_SPACE: ${{ vars.OCTOPUS_SPACE_NAME }}
      
    steps:
      - uses: OctopusDeploy/push-build-information-action@v3
        name: Push Build Information
        with:
          version: ${{ needs.package.outputs.version }}
          packages: |
            Octopub.Frontend

  create-release:
    name: Create release 🐙
    needs: [ package ] 
    runs-on: ubuntu-latest

    outputs:
      version: ${{ needs.package.outputs.version }}

    env:
      OCTOPUS_URL: ${{ vars.OCTOPUS_SERVER_URL }}
      OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
      OCTOPUS_SPACE: ${{ vars.OCTOPUS_SPACE_NAME }}

    steps:
      - name: Create a release in Octopus Deploy 🐙
        id: create-release
        uses: OctopusDeploy/create-release-action@v3
        with:
          project: 'Octopub Frontend'
          release_number: ${{ needs.package.outputs.version }}
          git_ref: ${{ (github.ref_type == 'tag' && github.event.repository.default_branch ) || (github.head_ref || github.ref) }}
          git_commit: ${{ github.event.after || github.event.pull_request.head.sha }}

  deploy-to-development:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [ create-release ] 
    name: "Deploy release ${{ needs.create-release.outputs.version }} to Development 🐙"
    outputs:
      server_tasks: ${{ steps.deploy-release-to-development.outputs.server_tasks }}

    env:
      OCTOPUS_URL: ${{ vars.OCTOPUS_SERVER_URL }}
      OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
      OCTOPUS_SPACE: ${{ vars.OCTOPUS_SPACE_NAME }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: OctopusDeploy/deploy-release-tenanted-action@v3
        id: "deploy-release-to-development"
        name: "Deploy release ${{ needs.create-release.outputs.version }} to Development 🐙"
        with:
          project: "Octopub Frontend"
          release_number: ${{ needs.create-release.outputs.version }}
          environment: "Development"
          tenant_tags: "Release Ring/Alpha"
      - id: "print-tasks"
        run: echo "${{ steps.deploy-release-to-development.outputs.server_tasks }}"

  wait-for-development:
    needs: [ create-release, deploy-to-development ]
    runs-on: ubuntu-latest
    name: "Wait for deployment of ${{ needs.create-release.outputs.version }} to Development to complete 🐙"
    strategy:
      matrix:
        value: ${{ fromJson(needs.deploy-to-development.outputs.server_tasks) }}

    env:
      OCTOPUS_URL: ${{ vars.OCTOPUS_SERVER_URL }}
      OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
      OCTOPUS_SPACE: ${{ vars.OCTOPUS_SPACE_NAME }}
  
    steps:
      - uses: OctopusDeploy/await-task-action@v3
        id: "wait-for-deploy-development"
        name: "Wait for deployment of ${{ needs.create-release.outputs.version }} to ${{ matrix.value.tenantName }} to complete 🐙"
        with:
          server_task_id: ${{ matrix.value.serverTaskId }}

  deploy-to-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [ create-release, wait-for-development ] 
    name: "Deploy release ${{ needs.create-release.outputs.version }} to Test 🐙"
    outputs:
      server_tasks: ${{ steps.deploy-release-to-test.outputs.server_tasks }}

    env:
      OCTOPUS_URL: ${{ vars.OCTOPUS_SERVER_URL }}
      OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
      OCTOPUS_SPACE: ${{ vars.OCTOPUS_SPACE_NAME }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: OctopusDeploy/deploy-release-tenanted-action@v3
        id: "deploy-release-to-test"
        name: "Deploy release ${{ needs.create-release.outputs.version }} to Test 🐙"
        with:
          project: "Octopub Frontend"
          release_number: ${{ needs.create-release.outputs.version }}
          environment: "Test"
          tenant_tags: "Release Ring/Alpha"
      - id: "print-tasks"
        run: echo "${{ steps.deploy-release-to-test.outputs.server_tasks }}"

  wait-for-test:
    needs: [ create-release, deploy-to-test ]
    runs-on: ubuntu-latest
    name: "Wait for deployment of ${{ needs.create-release.outputs.version }} to Test to complete 🐙"
    strategy:
      matrix:
        value: ${{ fromJson(needs.deploy-to-test.outputs.server_tasks) }}
  
    env:
      OCTOPUS_URL: ${{ vars.OCTOPUS_SERVER_URL }}
      OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
      OCTOPUS_SPACE: ${{ vars.OCTOPUS_SPACE_NAME }}
  
    steps:
      - uses: OctopusDeploy/await-task-action@v3
        id: "wait-for-deploy-development"
        name: "Wait for deployment of ${{ needs.create-release.outputs.version }} to ${{ matrix.value.tenantName }} to complete 🐙"
        with:
          server_task_id: ${{ matrix.value.serverTaskId }}
